export enum TagNames {
    MAIN = 'main',
    H1 = 'h1',
    H2 = 'h2',
    DIV = 'div',
    SECTION = 'section',
    SECTION_HEADER = DIV,
    SECTION_TITLE = 'label',
    TABLE_ITEM = DIV,
    CODE_WRAPPER = DIV,
    LEVEL_VIEWER = DIV,
    LEVEL_LIST = 'ul',
    LEVEL_LIST_ITEM = 'li',
    CSS_VIEWER_CONTROLS = DIV,
    INPUT = 'input',
    BUTTON = 'button',
    BOARD_LEVEL_ORDER = H2,
    IMAGE = 'img',
    TOOLTIP = SECTION_TITLE,
}
